version: "3.7"

networks:
  semaphore-net:
    driver: bridge

volumes:
  semaphore-postgres:
    driver: local

services:
  postgres:
    image: docker.io/library/postgres:latest
    hostname: postgres-sema
    networks:
      - semaphore-net
    volumes:
      - semaphore-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=semaphore
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=semaphore
    restart: unless-stopped

  semaphore:
    container_name: ansiblesemaphore
    image: semaphoreui/semaphore:latest
    user: "${UID}:${GID}"
    networks:
      - semaphore-net
    ports:
      - 3000:3000
    environment:
      - SEMAPHORE_DB_USER=semaphore
      - SEMAPHORE_DB_PASS=${SEMAPHORE_DB_PASS}
      - SEMAPHORE_DB_HOST=postgres-sema
      - SEMAPHORE_DB_PORT=5432
      - SEMAPHORE_DB_DIALECT=postgres
      - SEMAPHORE_DB=semaphore
      - SEMAPHORE_PLAYBOOK_PATH=/tmp/semaphore/
      - SEMAPHORE_ADMIN_PASSWORD=${SEMAPHORE_ADMIN_PASSWORD}
      - SEMAPHORE_ADMIN_NAME=admin
      - SEMAPHORE_ADMIN_EMAIL=${SEMAPHORE_ADMIN_EMAIL}
      - SEMAPHORE_ADMIN=admin
      - SEMAPHORE_ACCESS_KEY_ENCRYPTION=${SEMAPHORE_ACCESS_KEY_ENCRYPTION}
      - ANSIBLE_USER=${ANSIBLE_USER}
      - TZ=Europe/Berlin
    volumes:
      - /root/docker/semaphore/data:/var/lib/semaphore
      - /root/docker/semaphore/config:/etc/semaphore
      - /root/docker/semaphore/temp:/tmp/semaphore
    restart: unless-stopped
    depends_on:
      - postgres
