---
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest  # Image utilisée pour le service Transmission depuis LinuxServer.io
    container_name: transmission  # Nom du conteneur pour faciliter sa gestion
    
    environment:  # Variables d'environnement pour configurer Transmission
      - PUID=1000  # ID de l'utilisateur sous lequel le conteneur s'exécute (à aligner avec l'utilisateur de l'hôte pour les permissions)
      - PGID=1000  # ID du groupe sous lequel le conteneur s'exécute (à aligner avec le groupe de l'hôte)
      - TZ=Europe/Paris  # Fuseau horaire du conteneur
      - USER=test  # Nom d'utilisateur pour se connecter à Transmission (à personnaliser)
      - PASS=test  # Mot de passe pour l'utilisateur (à personnaliser pour la sécurité)
      - TRANSMISSION_WEB_UI=transmission-web-control  # Interface web utilisée par Transmission
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true  # Activation de l'authentification sur l'interface web
    
    volumes:  # Montage des volumes pour persister les données
      - /docker/transmission/data:/config  # Répertoire de configuration de Transmission
      - /docker/transmission/downloads:/downloads  # Répertoire où seront stockés les téléchargements
      - /docker/transmission/watch:/watch  # Répertoire surveillé pour les nouveaux fichiers torrent
    
    ports:  # Mappage des ports entre l'hôte et le conteneur
      - 9091:9091  # Port de l'interface web de Transmission
    
    restart: always  # Redémarrage automatique du conteneur en cas d'arrêt ou de plantage
