---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.9.3
    container_name: homepage
    environment:
      - LOG_LEVEL=info
    ports:
      - 3000:3000
    volumes:
      - /root/docker/homepage/config:/app/config
      - /root/docker/homepage/images:/app/images  # for custom background images
      - /root/docker/homepage/icons:/app/icons  # for custom icons
    restart: unless-stopped
