version: '3.8'

services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - heimdall_config:/config   # Utiliser le volume Docker nommé 'heimdall_config'
    ports:
      - ${HEIMDALL_PORT}:80       # Expose le port 80 du conteneur au port HEIMDALL_PORT de l’hôte
    restart: unless-stopped

volumes:
  heimdall_config:
    driver: local  # Spécifie le driver du volume (local par défaut)
